#config
Form-Title: "Welcome!"
Submit-Msg: "Submit"
Form-Content: "Welcome"
Btn1: "Rules"

UseFormInsteadOfChat: true
# set to false if you want to use chat instead of form as welcoming..

# Leave Message Values:
# {player} - gives player name

LeaveMessage: "{player} Has left the server"

LeaveMessageEnabled: true
